# Generated by Django 5.2.17 on 2026-10-07 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ORIGINAL', 'Original upload'), ('PROCESSED', 'Processed for the AI model')], max_length=10)),
                ('storage_bucket', models.CharField(default='voice-samples', max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('duration_sec', models.FloatField()),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voice_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='voices.voiceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['user', 'status'], name='voices_voic_user_id_86558b_idx'),
        ),
        migrations.AddConstraint(
            model_name='voiceprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_voice_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='voicesample',
            index=models.Index(fields=['voice_profile', 'kind', 'is_active'], name='voices_voic_voice_p_c9438d_idx'),
        ),
    ]
