# Generated by Django 5.2.17 on 2026-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesample',
            name='duration_sec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
