# Generated by Django 5.2.17 on 2026-10-07 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_name_snapshot', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('input_text', models.TextField()),
                ('char_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='voices.voiceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_bucket', models.CharField(default='generated-audio', max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('format', models.CharField(default='wav', max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='generations.generation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', '-created_at'], name='generations_user_id_800a84_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status'], name='generations_status_ae0db1_idx'),
        ),
    ]
